config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  resources :games do
    collection do
      get 'new_vs_ai', to: 'games#new_vs_ai'
      get 'new_vs_p', to: 'games#new_vs_p' # Route für Spiel gegen andere Spieler
      post 'create_vs_ai', to: 'games#create_vs_ai'
      post 'create_vs_p', to: 'games#create_vs_p' # Route für die Erstellung eines Spiels gegen einen Spieler
    end
  end

  resources :decks
  # Additional static pages
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user

  include PgSearch::Model

  pg_search_scope :search_by_country,
                  against: :country,
                  using: {
                    tsearch: { prefix: true }, # Erlaubt die Suche mit Präfix
                    trigram: { threshold: 0.1 } # Trigramm-Ähnlichkeitssuche
                  }
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :deck
  belongs_to :opponent, class_name: 'User', foreign_key: 'opponent_id'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  has_many :decks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show]

  def index
    if params[:query].present?
      # Verwende ein SQL-LIKE-Muster, um die Länderliste nach der Suchanfrage zu filtern
      @decks = Deck.where("country LIKE ?", "%#{params[:query]}%")
    else
      # Zeige alle Decks an, wenn keine Suchanfrage vorliegt
      @decks = Deck.all
    end
  end
  def show
    @decks = Deck.find(params[:id])
  end

  private

  def set_deck
    @deck = Deck.find(params[:id])
  end

  def deck_params
    params.require(:deck).permit(:name, :description)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show]

  # Zeigt ein Spiel an
  def show
    @game = Game.find(params[:id])
  end

  # Neues Spiel gegen einen menschlichen Spieler
  def new_vs_p
    @game = Game.new
    @game.user_id = current_user.id
    # Gegnerauswahl, alle Spieler außer der aktuelle Benutzer und die KI
    @opponents = User.where.not(id: current_user.id).where.not(email: 'john@ai.com')
  end

  # Neues Spiel gegen die KI
  def new_vs_ai
    @game = Game.new
    @game.user_id = current_user.id
    @game.status = 'ongoing'
    @opponent = User.find_by(email: 'john@ai.com') # Fester KI-Gegner
  end

  # Erstellen eines Spiels gegen die KI
  def create_vs_ai
    @game = Game.new(user_id: current_user.id, status: 'ongoing')
    @game.user_id = current_user.id
    @opponent = User.find_by(email: 'john@ai.com')
    @game.deck_id = current_user.decks.first.id if current_user.decks.any?

    Rails.logger.debug "Game attributes: #{@game.inspect}"# Finde den KI-Gegner

    if @opponent
      @game.opponent_id = @opponent.id # Setze den Gegner auf den KI-User (john@ai.com)

      if @game.save
        redirect_to @game, notice: 'Spiel gegen die KI wurde erfolgreich erstellt.' # Weiterleitung zur Spielansicht
      else
        flash.now[:alert] = 'Fehler beim Erstellen des Spiels.'
        render :new_vs_ai
      end
    else
      flash[:alert] = 'KI-Gegner wurde nicht gefunden.'
      render :new_vs_ai
    end
  end


  # Erstellen eines Spiels gegen einen menschlichen Spieler
  def create_vs_p
    @game = Game.new(game_params)
    @game.user_id = current_user.id
    @game.opponent_id = params[:game][:opponent_id]
    @game.deck_id = current_user.decks.first.id if current_user.decks.any? # ID des ausgewählten Gegners
    @game.status = 'ongoing'

    if @game.save
      redirect_to @game, notice: 'Spiel gegen einen Spieler wurde erstellt.'
    else
      flash.now[:alert] = 'Fehler beim Erstellen des Spiels. Bitte überprüfe deine Eingaben.'
      render :new_vs_p
    end
  end

  private

  # Spiel-Instanz setzen
  def set_game
    @game = Game.find(params[:id])
  end

  # Erlaubte Parameter für das Spiel
  def game_params
    params.require(:game).permit(:deck_id, :opponent_id) # opponent_id hinzugefügt
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!, only: [ :home ]
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/decks/index.html.erb
<h1>Liste der Länder</h1>

<div class="container-fluid">
  <%= form_with method: :get, local: true, class: "d-flex bk-none", role: "search" do %>
    <%= text_field_tag :query, params[:query], class: "form-control me-3", placeholder: "Type Country", aria: { label: "Search" } %>
    <%= submit_tag "Search", class: "btn btn-outline-danger" %>
  <% end %>
</div>

<% if @decks.empty? %>
  <p>Keine Ergebnisse gefunden.</p>
<% else %>
  <ul>
    <% @decks.each do |deck| %>
      <li>
        <%= link_to deck.country, deck_path(deck) %>
      </li>
    <% end %>
  </ul>
<% end %>
<%= link_to 'Zurück zur Startseite', root_path, class: 'btn btn-secondary' %>

app/views/decks/show.html.erb
<h1>Deck Details</h1>

<div class="deck-details">
  <p><strong>Land:</strong> <%= @deck.country %></p>
  <p><strong>Hauptstadt:</strong> <%= @deck.capital %></p>
  <p><strong>Einwohner der Hauptstadt:</strong> <%= @deck.inhabitants_of_the_capital %></p>
  <p><strong>Bruttoinlandsprodukt:</strong> <%= number_to_currency(@deck.gross_domestic_product, unit: "€") %></p>
  <p><strong>Waldfläche:</strong> <%= @deck.forest_area %> km²</p>
  <p><strong>Landfläche:</strong> <%= @deck.land_area %> km²</p>
  <p><strong>Straßennetz:</strong> <%= @deck.road_network %> km</p>
  <p><strong>Durchschnittliche Jahrestemperatur:</strong> <%= @deck.annual_temperature %> °C</p>
  <p><strong>Niederschlag:</strong> <%= @deck.precipitation %> mm</p>
  <p><strong>Bevölkerungsdichte:</strong> <%= @deck.population_density %> Personen/km²</p>
</div>

<%= link_to 'Zurück zur Übersicht', decks_path, class: 'btn btn-primary' %>

app/views/games/new_vs_ai.html.erb
<h1>Neues Spiel gegen John@KI </h1>

<%= form_with model: @game, url: create_vs_ai_games_path do |f| %>
  <%= f.submit "Spiel gegen die John starten", class: "btn btn-primary" %>
<% end %>

<%= link_to 'Zurück zur Spielübersicht', root_path, class: 'btn btn-secondary mt-3' %>

app/views/games/new_vs_p.html.erb
<h1> Spiel gegen einen anderen Spieler</h1>

<%= form_with model: @game, url: create_vs_p_games_path do |f| %>
  <div class="form-group mt-3">
    <%= f.label :opponent_id, "Wähle einen Gegner" %>
    <%= f.collection_select :opponent_id, @opponents, :id, :email, prompt: "Bitte wähle einen Gegner", class: "form-control" %>
  </div>

  <%= f.submit "Spiel starten", class: "btn btn-danger mt-3" %>
<% end %>

<%= link_to 'Zurück zur Spielübersicht', root_path, class: 'btn btn-secondary' %>

<%= form_with model: @game, local: true do |f| %>
  <div class="form-group">
    <%= f.label :opponent_id, "Wähle einen Gegner" %>
    <%= f.collection_select :opponent_id, @opponents, :id, :email, prompt: "Bitte wähle einen Gegner", class: "form-control" %>
  </div>

  <%= f.submit "Spiel starten", class: "btn btn-primary" %>
<% end %>

<%= form_with model: @game, url: create_vs_p_games_path do |f| %>
  <div class="form-group">
    <%= f.label :opponent_id, "Wähle einen Gegner" %>
    <%= f.collection_select :opponent_id, @opponents, :id, :email, prompt: "Bitte wähle einen Gegner", class: "form-control" %>
  </div>

  <%= f.submit "Spiel gegen Spieler starten", class: "btn btn-primary" %>
<% end %>

app/views/games/show.html.erb
<h1>Spiel: <%= @game.id %></h1>
<p>Status: <%= @game.status %></p>
<p>Punkte: <%= @game.points %></p>

<h2>Aktuelle Runde</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeoQuest</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>
    <%= render "shared/navbar" %>
    <div>
      <%= yield %>
      <br>
      <br>
      <br>
      <%= render "shared/flashes" %>
    </div>
    <div> <%= render "shared/footer" %></div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.pixabay.com/photo/2023/06/17/22/49/card-game-8070906_960_720.jpg);">
  <div class="container">
    <h1>GeoCode-Card-Deck</h1>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  with <i class="fas fa-heart"></i> from the Strong Kong Team
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
   <a class="navbar-brand" href="<%= root_path %>">
      <img src="https://cdn.pixabay.com/photo/2012/05/07/18/53/card-game-48983_960_720.png" />
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <strong><%= link_to "Info of Decks", decks_path, class: "nav-link" %></strong>
          </li>
          <li class="nav-item">
          <strong><%= link_to "Game vs John@KI", new_vs_ai_games_path, class: "nav-link" %></strong>
          </li>
          <li class="nav-item">
          <strong><%= link_to "Game vs Player", new_vs_p_games_path, class: "nav-link" %></strong>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://cdn.pixabay.com/photo/2016/08/28/13/12/secondlife-1625903_960_720.jpg" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" data-turbo-method="delete" href="<%= destroy_user_session_path %>">Log out</a>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= form_with url: user_session_path, local: true, class: 'form-inline' do |form| %>
              <%= form.submit 'Login', class: 'btn btn-danger my-2 my-sm-0' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>